### ISSUE TITLE
build v2012.4 on linux-headers-4.14.18-sunxi 

### ISSUE THREAD

**Issue by mcsa2003** [freifunk-gluon/batman-adv-legacy#12]
got some errors when i recently try to build batman-adv v2012.4 for  linux-headers-4.14.18-sunxi 

  CC [M]  /root/batman-adv-legacy-2012.4.0/bat_iv_ogm.o
In file included from /root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:23:0:
/root/batman-adv-legacy-2012.4.0/originator.h: In function ‘batadv_orig_hash_find’:
/root/batman-adv-legacy-2012.4.0/originator.h:82:60: error: macro "hlist_for_each_entry_rcu" passed 4 arguments, but takes just 3
  hlist_for_each_entry_rcu(orig_node, node, head, hash_entry) {
                                                            ^
/root/batman-adv-legacy-2012.4.0/originator.h:82:2: error: ‘hlist_for_each_entry_rcu’ undeclared (first use in this function)
  hlist_for_each_entry_rcu(orig_node, node, head, hash_entry) {
  ^
/root/batman-adv-legacy-2012.4.0/originator.h:82:2: note: each undeclared identifier is reported only once for each function it appears in
/root/batman-adv-legacy-2012.4.0/originator.h:82:62: error: expected ‘;’ before ‘{’ token
  hlist_for_each_entry_rcu(orig_node, node, head, hash_entry) {
                                                              ^
/root/batman-adv-legacy-2012.4.0/originator.h:72:27: warning: unused variable ‘orig_node’ [-Wunused-variable]
  struct batadv_orig_node *orig_node, *orig_node_tmp = NULL;
                           ^
/root/batman-adv-legacy-2012.4.0/originator.h:71:21: warning: unused variable ‘node’ [-Wunused-variable]
  struct hlist_node *node;
                     ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c: In function ‘batadv_iv_ogm_emit_send_time’:
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:122:12: error: implicit declaration of function ‘random32’ [-Werror=implicit-function-declaration]
  msecs += (random32() % 2 * BATADV_JITTER);
            ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c: In function ‘batadv_iv_ogm_queue_add’:
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:501:40: error: macro "hlist_for_each_entry" passed 4 arguments, but takes just 3
          &bat_priv->forw_bat_list, list) {
                                        ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:500:3: error: ‘hlist_for_each_entry’ undeclared (first use in this function)
   hlist_for_each_entry(forw_packet_pos, tmp_node,
   ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:501:42: error: expected ‘;’ before ‘{’ token
          &bat_priv->forw_bat_list, list) {
                                          ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:487:21: warning: unused variable ‘tmp_node’ [-Wunused-variable]
  struct hlist_node *tmp_node;
                     ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:486:29: warning: unused variable ‘forw_packet_pos’ [-Wunused-variable]
  struct batadv_forw_packet *forw_packet_pos = NULL;
                             ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c: In function ‘batadv_iv_ogm_orig_update’:
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:665:34: error: macro "hlist_for_each_entry_rcu" passed 4 arguments, but takes just 3
      &orig_node->neigh_list, list) {
                                  ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:664:2: error: ‘hlist_for_each_entry_rcu’ undeclared (first use in this function)
  hlist_for_each_entry_rcu(tmp_neigh_node, node,
  ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:665:36: error: expected ‘;’ before ‘{’ token
      &orig_node->neigh_list, list) {
                                    ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:784:1: warning: label ‘unlock’ defined but not used [-Wunused-label]
 unlock:
 ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:658:10: warning: unused variable ‘tq_avg’ [-Wunused-variable]
  uint8_t tq_avg;
          ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:657:11: warning: unused variable ‘neigh_addr’ [-Wunused-variable]
  uint8_t *neigh_addr;
           ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:654:21: warning: unused variable ‘node’ [-Wunused-variable]
  struct hlist_node *node;
                     ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:651:48: warning: unused variable ‘tmp_neigh_node’ [-Wunused-variable]
  struct batadv_neigh_node *neigh_node = NULL, *tmp_neigh_node = NULL;
                                                ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c: In function ‘batadv_iv_ogm_calc_tq’:
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:810:40: error: macro "hlist_for_each_entry_rcu" passed 4 arguments, but takes just 3
      &orig_neigh_node->neigh_list, list) {
                                        ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:809:2: error: ‘hlist_for_each_entry_rcu’ undeclared (first use in this function)
  hlist_for_each_entry_rcu(tmp_neigh_node, node,
  ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:810:42: error: expected ‘;’ before ‘{’ token
      &orig_neigh_node->neigh_list, list) {
                                          ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:800:21: warning: unused variable ‘node’ [-Wunused-variable]
  struct hlist_node *node;
                     ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:799:48: warning: unused variable ‘tmp_neigh_node’ [-Wunused-variable]
  struct batadv_neigh_node *neigh_node = NULL, *tmp_neigh_node;
                                                ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c: In function ‘batadv_iv_ogm_update_seqnos’:
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:944:34: error: macro "hlist_for_each_entry_rcu" passed 4 arguments, but takes just 3
      &orig_node->neigh_list, list) {
                                  ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:943:2: error: ‘hlist_for_each_entry_rcu’ undeclared (first use in this function)
  hlist_for_each_entry_rcu(tmp_neigh_node, node,
  ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:944:36: error: expected ‘;’ before ‘{’ token
      &orig_node->neigh_list, list) {
                                    ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:927:10: warning: unused variable ‘packet_count’ [-Wunused-variable]
  uint8_t packet_count;
          ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:926:11: warning: unused variable ‘neigh_addr’ [-Wunused-variable]
  uint8_t *neigh_addr;
           ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:924:6: warning: unused variable ‘set_mark’ [-Wunused-variable]
  int set_mark, ret = -1;
      ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:920:21: warning: unused variable ‘node’ [-Wunused-variable]
  struct hlist_node *node;
                     ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:919:28: warning: unused variable ‘tmp_neigh_node’ [-Wunused-variable]
  struct batadv_neigh_node *tmp_neigh_node;
                            ^
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c: At top level:
/root/batman-adv-legacy-2012.4.0/bat_iv_ogm.c:297:1: warning: ‘batadv_iv_ogm_can_aggregate’ defined but not used [-Wunused-function]
 batadv_iv_ogm_can_aggregate(const struct batadv_ogm_packet *new_bat_ogm_packet,

**Comment by NeoRaider** [comment]
This repository is based on batman-adv 2013.4. As far as I understand it from the log you posted, the version you are building is not based on this repository.
