### ISSUE TITLE
batman-adv-legacy and OpenWRT v12.09

### ISSUE THREAD

**Issue by sp2ong** [freifunk-gluon/batman-adv-legacy#9]
Hi,

I want to switch our local mesh network form OLSRD to BATMAN but we still uss old routers like Ubiquiti Nanostation 2 or 5 which working very well on OWRT 12.09. In OWRT 12.09 last version BATMAN is available v2013.4. I have compile  Batman-adv-legacy with OWRT 12.09 but without success. 

Anybody know it is possible compile this package with OWRT v12.09  ????

Regards

**Comment by T-X** [comment]
Hi sp2ong. This package is ment for people already using batman-adv, who did not have the chance to upgrade yet. It is not intended for new installations. If you want to switch your mesh network protocol, then please use a recent batman-adv version. Maintenance of this package from Freifunk people will stop once we have migrated the last installations (which aren't many anymore).

This is probably not the answer you were looking for, sorry :-(. If you need any help installing a recent batman-adv version, feel free to stop by on IRC at #batman on Freenode or the batman-adv mailing list.
